CREATE TABLE squared_squirrel_users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    games_played INTEGER NOT NULL DEFAULT 0,
    lowest_time_win INTEGER
);