CREATE TABLE squared_squirrel_users_statistics (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES squared_squirrel_users(id) ON DELETE CASCADE NOT NULL,
    games_played INTEGER NOT NULL DEFAULT 0,
    games_won INTEGER NOT NULL DEFAULT 0,
    lowest_time_win INTEGER DEFAULT 0
);